project:
  type: website
  resources:
    - sangf_cv.pdf
  output-dir: docs
  execute-dir: project
  
website:
  title: "Feng Sang"
  navbar:
    background: primary
    search: true
    right:
      - text: "HOME"
        href: index.qmd
      - text: "PAPERS"
        href: papers.qmd
      - text: "BOLGS"
        href: blogs.qmd
  page-footer: 
    left: 
      - text: "&copy; Copyright 2021-2024, Feng Sang"
    border: true
  reader-mode: true
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false
      
format:
  html:
    theme: [sandstone, _variables.scss]
    css: styles.css
    toc: true

execute:
  freeze: auto
